### ISSUE TITLE
Optimized rust code

### ISSUE THREAD

**Issue by rxdiscovery** [pjgg/javaJwtSignExample#1]
Hello,

I've uploaded the project source code + a video + the result : 

https://github.com/rxdiscovery/rust_jwt_bench_v1/

Best regards.

**Comment by pjgg** [comment]
Thank you @rxdiscovery quite impressive the Rust multi/thread performance

**Comment by enyineer** [comment]
I had already been wondering why someone would optimize the Java code for multithreading, only to make an even worse comparison than before in an attempt to disprove something. Thank you, @rxdiscovery, for demonstrating that the original author is still correct and that, in this specific example, Java is 38 times less efficient than Rust.
